### ISSUE TITLE
'tuple index out of range' in NumpyMultiVector.__len__

### ISSUE THREAD

**Issue by RichardPotthoff** [EelcoHoogendoorn/numga#4]
When I tried to run the 'run_chain_numpy.py' example, I got the following error:
```python
NumpyMultiVector.__len__(self)
     45 def __len__(self):
---> 46 	return self.shape[0]

IndexError: tuple index out of range
```
I was able to fix this by returning `1` if it `self.shape` is an empty tuple:
```python
   45  def __len__(self):
   46    if len(self.shape)==0:
   47      return 1
   48    else:
   49      return self.shape[0]
```
This worked, but I am not sure if `self.shape` should  ever have been an empty tuple to begin with. Maybe the real error is somewhere else?

**Comment by EelcoHoogendoorn** [comment]
Hey, thanks for the feedback.

Works on my machine... but it seems I had some unpushed changes to the broadcasting logic in physics/base.py

The semantics of self.shape should allow for an empty tuple; the same way as numpy/jax would treat a zero-dimensioned array:

```
>>> len(np.array(1))
Traceback (most recent call last):
  File "/Users/eelco/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-C/ch-0/232.9559.58/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
TypeError: len() of unsized object
```

**Comment by RichardPotthoff** [comment]
Interesting!
It seems it is not easy to get the element of a zero-dimensional numpy array back in it's original form:

```python
>>> np.array(1)[0]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

>>> np.array(1)[]
  File "<string>", line 1
    np.array(1)[]
                ^
SyntaxError: invalid syntax

>>> np.array(1)[None]
array([1])

>>> np.array(1)[()]
1

>>> np.array(1)[[]]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

>>> np.array(1).__getitem__()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: expected 1 argument, got 0
```

Passing an empty tuple as the array index seems to be the only way.

**Comment by EelcoHoogendoorn** [comment]
Casting to the non-numpy type is what I usually see done in such a context.
```float(np.array(1))```
Though I like the empty index better, since the above mixes the unpacking and a typecast, which may not be desirable.

A shape==() numga Multivector is intended to behave in all ways as a shape==() numpy array; the fact that it has an extra hidden dimension containing the multivector components should matter as little to the high level semantics of the library as that a complex type has a real and imag component. Thats the ideal at least.

**Comment by RichardPotthoff** [comment]
I just ran the `run_chain_numpy.py` again, and it's running without errors.
Your commit 62a5560 has solved the problem.
