### ISSUE TITLE
'divide by zero' warning when running 'test_circle_reflect' test in 'test_conformal.py'

### ISSUE THREAD

**Issue by RichardPotthoff** [EelcoHoogendoorn/numga#5]
I get the following warning when I run the `test_circle_reflect` example:
```python
/private/var/mobile/Containers/Data/Application/77881549-3FA6-4E4B-803F-D53B172FC865/Documents/myrepo/
numga/multivector/multivector.py:311: 
RuntimeWarning: divide by zero encountered in divide
  return self.copy(values=self.values / other.values)
```
This is only a warning, so I am not sure if it is a bug.

I suspect the reason for the 'divide by zero' warning is that the center of one of the mirrored circles is at the origin. 
There is also a circle with a radius of 5e14 (presumably infinity) being drawn, and I had to set xlim and ylim to +-40 to zoom in to see the other circles.

**Comment by EelcoHoogendoorn** [comment]
Cant say that the polish has reached a level where im catching all warnings; though id be open to PRs that try to stamp them out. Seems you are correct about where that warning is coming from.

The detault plotting behavior is reasonable with my env; but youd probably also want to zoom and and knowing it can freak out it is indeed better to add a fixed limit.
